### ISSUE TITLE
`createdir` stops to work 

### ISSUE THREAD

**Issue by cnlangzi** [0chain/gosdk#537]
```
./zbox createdir --dirname "/new_folder" --allocation "8fadceafe4d6220ca190af4d40b1407392818269247ef4ca6f58f91f158c54d0"
0chain-core-sdk [INFO]   2022/08/12 17:19:15.544645 wallet.go:290: ******* Wallet SDK Version:v1.7.2-2-g3237f5c-dirty ******* (SetLogFile)
0box-sdk        [INFO]   2022/08/12 17:19:15.544769 sdk.go:73: ******* Storage SDK Version: v1.7.2-2-g3237f5c-dirty *******
0chain-core-sdk [INFO]   2022/08/12 17:19:16.444311 wallet.go:413: ******* Wallet SDK Version:v1.7.2-2-g3237f5c-dirty ******* (InitZCNSDK)
0box-sdk        [DEBUG]  2022/08/12 17:19:17.269600 networkworker.go:105: Get network result:{"miners":["https://demo.0chain.net/miner02","https://demo.0chain.net/miner01","https://demo.0chain.net/miner03"],"sharders":["https://demo.0chain.net/sharder02","https://demo.0chain.net/sharder01"]}
0box-sdk        [INFO]   2022/08/12 17:19:17.862019 dirworker.go:45: Start creating dir for blobbers
0box-sdk        [INFO]   2022/08/12 17:19:18.089465 dirworker.go:146: createdir resp:{"filename":"/new_folder","size":0,"content_hash":"","merkle_root":"","upload_length":0,"upload_offset":0}
0box-sdk        [INFO]   2022/08/12 17:19:18.089733 dirworker.go:151: https://demo.0chain.net/blobber04 /new_folder created.
0box-sdk        [INFO]   2022/08/12 17:19:18.092505 dirworker.go:146: createdir resp:{"filename":"/new_folder","size":0,"content_hash":"","merkle_root":"","upload_length":0,"upload_offset":0}
0box-sdk        [INFO]   2022/08/12 17:19:18.092556 dirworker.go:151: https://demo.0chain.net/blobber05 /new_folder created.
0box-sdk        [INFO]   2022/08/12 17:19:18.304308 dirworker.go:146: createdir resp:{"filename":"/new_folder","size":0,"content_hash":"","merkle_root":"","upload_length":0,"upload_offset":0}
0box-sdk        [INFO]   2022/08/12 17:19:18.304400 dirworker.go:151: https://demo.0chain.net/blobber02 /new_folder created.
0box-sdk        [INFO]   2022/08/12 17:19:18.304361 dirworker.go:146: createdir resp:{"filename":"/new_folder","size":0,"content_hash":"","merkle_root":"","upload_length":0,"upload_offset":0}
0box-sdk        [INFO]   2022/08/12 17:19:18.304433 dirworker.go:151: https://demo.0chain.net/blobber01 /new_folder created.
0box-sdk        [INFO]   2022/08/12 17:19:19.852354 commitworker.go:102: received a commit request
0box-sdk        [INFO]   2022/08/12 17:19:19.852253 commitworker.go:102: received a commit request
0box-sdk        [INFO]   2022/08/12 17:19:19.852297 commitworker.go:102: received a commit request
0box-sdk        [INFO]   2022/08/12 17:19:19.852382 commitworker.go:102: received a commit request
panic: interface conversion: fileref.RefEntity is *fileref.FileRef, not *fileref.Ref

goroutine 55 [running]:
github.com/0chain/gosdk/zboxcore/allocationchange.(*DirCreateChange).ProcessChange(0x103678940?, 0x14000284000)
	/Users/rj/go/pkg/mod/github.com/0chain/gosdk@v1.8.6-0.20220727101848-c573a174d64b/zboxcore/allocationchange/createdir.go:24 +0x2d0
github.com/0chain/gosdk/zboxcore/sdk.(*CommitRequest).processCommit(0x1400069e6c0)
	/Users/rj/go/pkg/mod/github.com/0chain/gosdk@v1.8.6-0.20220727101848-c573a174d64b/zboxcore/sdk/commitworker.go:183 +0x62c
github.com/0chain/gosdk/zboxcore/sdk.startCommitWorker(0x0?, {0x140002ea6c0, 0x40})
	/Users/rj/go/pkg/mod/github.com/0chain/gosdk@v1.8.6-0.20220727101848-c573a174d64b/zboxcore/sdk/commitworker.go:94 +0x3c
created by github.com/0chain/gosdk/zboxcore/sdk.InitCommitWorker
	/Users/rj/go/pkg/mod/github.com/0chain/gosdk@v1.8.6-0.20220727101848-c573a174d64b/zboxcore/sdk/commitworker.go:82 +0x298
```

**Comment by cnlangzi** [comment]
```
2wasm_exec.js:53 0box-sdk [INFO]   2022/08/25 02:44:54.415000 dirworker.go:45: Start creating dir for blobbers
2wasm_exec.js:53 0box-sdk [INFO]   2022/08/25 02:44:54.906000 dirworker.go:146: createdir resp:{"filename":"/New Folder","size":0,"content_hash":"","merkle_root":"","upload_length":0,"upload_offset":0}
2wasm_exec.js:53 0box-sdk [INFO]   2022/08/25 02:44:54.907000 dirworker.go:151: https://dev.0chain.net/blobber02 /New Folder created.
2wasm_exec.js:53 0box-sdk [INFO]   2022/08/25 02:44:54.909000 dirworker.go:146: createdir resp:{"filename":"/New Folder","size":0,"content_hash":"","merkle_root":"","upload_length":0,"upload_offset":0}
2wasm_exec.js:53 0box-sdk [INFO]   2022/08/25 02:44:54.909000 dirworker.go:151: https://dev.0chain.net/blobber06 /New Folder created.
2wasm_exec.js:53 0box-sdk [INFO]   2022/08/25 02:44:54.947000 dirworker.go:146: createdir resp:{"filename":"/New Folder","size":0,"content_hash":"","merkle_root":"","upload_length":0,"upload_offset":0}
2wasm_exec.js:53 0box-sdk [INFO]   2022/08/25 02:44:54.947000 dirworker.go:151: https://dev.0chain.net/blobber03 /New Folder created.
2wasm_exec.js:53 0box-sdk [INFO]   2022/08/25 02:44:54.949000 dirworker.go:146: createdir resp:{"filename":"/New Folder","size":0,"content_hash":"","merkle_root":"","upload_length":0,"upload_offset":0}
2wasm_exec.js:53 0box-sdk [INFO]   2022/08/25 02:44:54.949000 dirworker.go:151: https://dev.0chain.net/blobber04 /New Folder created.
8wasm_exec.js:53 0box-sdk [INFO]   2022/08/25 02:44:56.395000 commitworker.go:102: received a commit request
wasm_exec.js:53 panic: interface conversion: fileref.RefEntity is *fileref.FileRef, not *fileref.Ref
wasm_exec.js:53 
wasm_exec.js:53 goroutine 35 [running]:
wasm_exec.js:53 github.com/0chain/gosdk/zboxcore/allocationchange.(*DirCreateChange).ProcessChange(0xfcdba0, 0xdccfc0)
wasm_exec.js:53 	/Users/geax/code/geax/github.com/0chain/gosdk/zboxcore/allocationchange/createdir.go:24 +0x33
wasm_exec.js:53 github.com/0chain/gosdk/zboxcore/sdk.(*CommitRequest).processCommit(0xfde180)
wasm_exec.js:53 	/Users/geax/code/geax/github.com/0chain/gosdk/zboxcore/sdk/commitworker.go:183 +0xa2
wasm_exec.js:53 github.com/0chain/gosdk/zboxcore/sdk.startCommitWorker(0xe656e0, {0xeee680, 0x40})
wasm_exec.js:53 	/Users/geax/code/geax/github.com/0chain/gosdk/zboxcore/sdk/commitworker.go:94 +0x3
wasm_exec.js:53 created by github.com/0chain/gosdk/zboxcore/sdk.InitCommitWorker
wasm_exec.js:53 	/Users/geax/code/geax/github.com/0chain/gosdk/zboxcore/sdk/commitworker.go:82 +0x26
wasm_exec.js:153 exit code: 2
exit @ wasm_exec.js:153
runtime.wasmExit @ wasm_exec.js:277
$runtime.wasmExit @ zcn.wasm:0xf1c27
$runtime.exit @ zcn.wasm:0xf1a55
$runtime.fatalpanic.func2 @ zcn.wasm:0x89c32
$runtime.systemstack @ zcn.wasm:0xeefc2
$runtime.fatalpanic @ zcn.wasm:0x89d95
$runtime.gopanic @ zcn.wasm:0x88725
$runtime.panicdottypeI @ zcn.wasm:0x1e584
$github.com_0chain_gosdk_zboxcore_allocationchange.__DirCreateChange_.ProcessChange @ zcn.wasm:0x8ab1a9
$github.com_0chain_gosdk_zboxcore_sdk.__CommitRequest_.processCommit @ zcn.wasm:0x93a63e
$wasm_pc_f_loop @ zcn.wasm:0xf1a0e
$wasm_export_resume @ zcn.wasm:0xf19ef
```

reported it on https://0chain.slack.com/archives/G01EXH6EYC9/p1661378095133829
